/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Internal;

import java.awt.Color;
import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author PC
 */
public class Edit_1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Edit_1
     */
    public Edit_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        StudentNametf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        FatherNametf = new javax.swing.JTextField();
        DOB = new javax.swing.JTextField();
        StudentMobiletf = new javax.swing.JTextField();
        FatherCNICtf = new javax.swing.JTextField();
        BFormtf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        FatherMobiletf = new javax.swing.JTextField();
        Programtf = new javax.swing.JTextField();
        Packagetf = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        FirstInstallmenttf = new javax.swing.JTextField();
        MatricRolltf = new javax.swing.JTextField();
        MatricMarkstf = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        AdmissionDatetf = new javax.swing.JTextField();
        AdmissionBytf = new javax.swing.JTextField();
        ApproachedBytf = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        EnteredBytf = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        Statustf = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        Malecheck = new javax.swing.JRadioButton();
        FemaleCheck = new javax.swing.JRadioButton();
        Registerbtn = new javax.swing.JButton();
        Cancelbtn = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        Jpanel.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Update Student Record");

        StudentNametf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentNametfActionPerformed(evt);
            }
        });

        jLabel3.setText("Student Full Name");

        jLabel4.setText("FatherName");

        jLabel5.setText("DOB");

        FatherNametf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FatherNametfActionPerformed(evt);
            }
        });

        DOB.setAlignmentX(0.0F);
        DOB.setMinimumSize(new java.awt.Dimension(64, 30));

        StudentMobiletf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentMobiletfActionPerformed(evt);
            }
        });

        FatherCNICtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FatherCNICtfActionPerformed(evt);
            }
        });

        BFormtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFormtfActionPerformed(evt);
            }
        });

        jLabel6.setText("BFormNo");

        jLabel7.setText("StudentMobile");

        jLabel8.setText("FatherCNIC");

        jLabel9.setText("FatherMobile");

        jLabel10.setText("Program");

        jLabel11.setText("Package");

        Packagetf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PackagetfActionPerformed(evt);
            }
        });

        jLabel12.setText("First Installment");

        jLabel13.setText("Matric RollNo");

        jLabel14.setText("Matric Marks");

        jLabel15.setText("Admission Date");

        jLabel16.setText("Admission By");

        jLabel17.setText("Approached By");

        AdmissionBytf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdmissionBytfActionPerformed(evt);
            }
        });

        jLabel18.setText("Entered By");

        jLabel19.setText("Status");

        jLabel20.setText("Gender");

        Malecheck.setText("Male");

        FemaleCheck.setText("Female");

        Registerbtn.setBackground(new java.awt.Color(153, 153, 255));
        Registerbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Registerbtn.setForeground(new java.awt.Color(255, 255, 255));
        Registerbtn.setText("Update");
        Registerbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Registerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterbtnActionPerformed(evt);
            }
        });

        Cancelbtn.setBackground(new java.awt.Color(153, 153, 255));
        Cancelbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Cancelbtn.setForeground(new java.awt.Color(255, 255, 255));
        Cancelbtn.setText("Cancel");
        Cancelbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelbtnActionPerformed(evt);
            }
        });

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpanelLayout = new javax.swing.GroupLayout(Jpanel);
        Jpanel.setLayout(JpanelLayout);
        JpanelLayout.setHorizontalGroup(
            JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
            .addGroup(JpanelLayout.createSequentialGroup()
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(FirstInstallmenttf, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AdmissionDatetf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(FatherMobiletf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BFormtf, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(StudentNametf, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addGap(67, 67, 67)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpanelLayout.createSequentialGroup()
                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AdmissionBytf, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(MatricRolltf, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(StudentMobiletf, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(39, 39, 39)
                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(MatricMarkstf, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ApproachedBytf, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel14)
                            .addComponent(Statustf, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DOB, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addComponent(Programtf, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JpanelLayout.createSequentialGroup()
                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpanelLayout.createSequentialGroup()
                                .addComponent(FatherNametf, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpanelLayout.createSequentialGroup()
                                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(JpanelLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel20))
                                    .addComponent(Malecheck))
                                .addGap(18, 18, 18)))
                        .addComponent(FemaleCheck)
                        .addGap(42, 42, 42)))
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EnteredBytf, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(FatherCNICtf, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(Packagetf, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(JpanelLayout.createSequentialGroup()
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpanelLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(Registerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(Cancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JpanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JpanelLayout.setVerticalGroup(
            JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(64, 64, 64)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel20))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StudentNametf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FatherNametf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Malecheck)
                    .addComponent(FemaleCheck))
                .addGap(33, 33, 33)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FatherCNICtf, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(DOB, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(StudentMobiletf, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(BFormtf, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel19)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FatherMobiletf, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Programtf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Statustf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Packagetf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstInstallmenttf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MatricRolltf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MatricMarkstf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnteredBytf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdmissionDatetf, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdmissionBytf, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ApproachedBytf, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Registerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StudentNametfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentNametfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentNametfActionPerformed

    private void FatherNametfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FatherNametfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FatherNametfActionPerformed

    private void StudentMobiletfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentMobiletfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentMobiletfActionPerformed

    private void FatherCNICtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FatherCNICtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FatherCNICtfActionPerformed

    private void BFormtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFormtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BFormtfActionPerformed

    private void PackagetfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PackagetfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PackagetfActionPerformed

    private void AdmissionBytfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdmissionBytfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdmissionBytfActionPerformed

    private void RegisterbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterbtnActionPerformed
            final String DB_URL = "jdbc:mysql://localhost:3306/Person?serverTimezone=UTC";
            final String USERNAME = "root";
            final String PASSWORD = "Muneeb@1372";
        
                Connection con;
        try {
                con = DriverManager.getConnection(DB_URL,USERNAME,PASSWORD);
                String sql = "Update Student SET stname = ? ,FatherName=?,DOB=?, BForm = ?, StMobile = ?  , "
                        + "FCNIC = ? , FMobile = ? , Program = ? , Package = ? , FirstInstallment = ?,"
                        + "MatricRoll = ? , DateOfAdmission = ? , MatricMarks = ?,"
                        + "AdmissionBy= ? , ApproachedBy = ? , EnteredBy = ? WHERE BForm = ?";
                          
                PreparedStatement pr_st = con.prepareStatement(sql);
                
                pr_st.setString(1,StudentNametf.getText());
                pr_st.setString(2,FatherNametf.getText());
                
                pr_st.setString(3,DOB.getText());
                
                
                        pr_st.setString(4,BFormtf.getText());
                
                        pr_st.setString(5,StudentMobiletf.getText());
                
                        pr_st.setString(6,FatherCNICtf.getText());
                        
                        pr_st.setString(7,FatherMobiletf.getText());
                        
                        pr_st.setString(8,Programtf.getText());
                        
                        
                        pr_st.setString(9,Packagetf.getText());
                        
                        
                        pr_st.setString(10,FirstInstallmenttf.getText());
                        
                        
                        pr_st.setString(11,MatricRolltf.getText());
                        
                        pr_st.setString(12,AdmissionDatetf.getText());
                        
                        pr_st.setString(13,MatricMarkstf.getText());
                        
                        
                        pr_st.setString(14,AdmissionBytf.getText());
                        
                        pr_st.setString(15,ApproachedBytf.getText());
                        
                        
                        pr_st.setString(16,EnteredBytf.getText());
                        
                        
                        //pr_st.setString(17,EnteredBytf.getText());
                        
                        pr_st.setString(17,BFormtf.getText());
                        
                        
                int num = pr_st.executeUpdate();
                JOptionPane.showMessageDialog(null, num+"Record Updated");
//                    StudentNametf.setText(str);
//                    FatherNametf.setText(str_1);
//                    DOB.setText(str_2);  
//                    BFormtf.setText(str_3);
//                    StudentMobiletf.setText(str_5);
//                    FatherCNICtf.setText(str_6);
//                    FatherMobiletf.setText(str_7);
//                    Programtf.setText(str_8);
//                    Packagetf.setText(str_9);
//                    FirstInstallmenttf.setText(str_10);
//                    MatricRolltf.setText(str_11);
//                    AdmissionDatetf.setText(str_12);
//                    MatricMarkstf.setText(str_13);
//                    AdmissionBytf.setText(str_14);
//                    ApproachedBytf.setText(str_15);
//                    EnteredBytf.setText(str_16);
//        
        } catch (SQLException ex) {
            Logger.getLogger(Edit_1.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }//GEN-LAST:event_RegisterbtnActionPerformed

    private void CancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelbtnActionPerformed
        dispose();
    }//GEN-LAST:event_CancelbtnActionPerformed

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        if(jTextField1.getText().equals(""))
        {
            jTextField1.setText("Enter Student BForm Number");
            jTextField1.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        if(jTextField1.getText().equals("Enter Student BForm Number"))
        {
            jTextField1.setText("");
            jTextField1.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTextField1FocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            final String DB_URL = "jdbc:mysql://localhost:3306/Person?serverTimezone=UTC";
            final String USERNAME = "root";
            final String PASSWORD = "Muneeb@1372";
        try {
                Connection con = DriverManager.getConnection(DB_URL,USERNAME,PASSWORD);
                String sql = "Select * from Student";    
                PreparedStatement pr_st = con.prepareStatement(sql);
                //pr_st.setString(1, jTextField1.getText());
                ResultSet rs = pr_st.executeQuery();
                boolean a =false;
                String q = jTextField1.getText();
                while(rs.next())
                {
                    if(jTextField1.getText().equals(rs.getString("BForm")))
                        a = true;
                }
                if(a==true)
                {
                        String sql_1 = "Select * from Student where BForm=?";    
                        PreparedStatement pr_st_1 = con.prepareStatement(sql_1);
                        pr_st_1.setString(1, jTextField1.getText());
                        ResultSet rs_1 = pr_st_1.executeQuery();
                        rs_1.next();
                        String str = rs_1.getString("stname");
                    String str_1 = rs_1.getString("FatherName");
                    String str_2 = rs_1.getString("DOB");
                    String str_3 = rs_1.getString("BForm");
                    String str_4 = rs_1.getString("gender");
                    String str_5 = rs_1.getString("StMobile");
                    String str_6 = rs_1.getString("FCNIC");
                    String str_7 = rs_1.getString("FMobile");
                    String str_8 = rs_1.getString("Program");
                    String str_9 = rs_1.getString("Package");
                    String str_10 = rs_1.getString("FirstInstallment");
                    String str_11 = rs_1.getString("MatricRoll");
                    String str_12 = rs_1.getString("DateOfAdmission");
                    String str_13 = rs_1.getString("MatricMarks");
                    String str_14 = rs_1.getString("AdmissionBy");
                    String str_15 = rs_1.getString("ApproachedBy");
                    String str_16 =  rs_1.getString("EnteredBy");
                    //                 rs.getString("Status");
                    StudentNametf.setText(str);
                    FatherNametf.setText(str_1);
                    DOB.setText(str_2);  
                    BFormtf.setText(str_3);
                    StudentMobiletf.setText(str_5);
                    FatherCNICtf.setText(str_6);
                    FatherMobiletf.setText(str_7);
                    Programtf.setText(str_8);
                    Packagetf.setText(str_9);
                    FirstInstallmenttf.setText(str_10);
                    MatricRolltf.setText(str_11);
                    AdmissionDatetf.setText(str_12);
                    MatricMarkstf.setText(str_13);
                    AdmissionBytf.setText(str_14);
                    ApproachedBytf.setText(str_15);
                    EnteredBytf.setText(str_16);
                }else
                {
                    JOptionPane.showMessageDialog(null, "Please enter valid BForm Number");
                }  
        }catch (SQLException ex) {
            Logger.getLogger(Edit_1.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
            
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField AdmissionBytf;
    public javax.swing.JTextField AdmissionDatetf;
    public javax.swing.JTextField ApproachedBytf;
    public javax.swing.JTextField BFormtf;
    private javax.swing.JButton Cancelbtn;
    private javax.swing.JTextField DOB;
    public javax.swing.JTextField EnteredBytf;
    public javax.swing.JTextField FatherCNICtf;
    public javax.swing.JTextField FatherMobiletf;
    private javax.swing.JTextField FatherNametf;
    private javax.swing.JRadioButton FemaleCheck;
    public javax.swing.JTextField FirstInstallmenttf;
    private javax.swing.JPanel Jpanel;
    private javax.swing.JRadioButton Malecheck;
    public javax.swing.JTextField MatricMarkstf;
    public javax.swing.JTextField MatricRolltf;
    public javax.swing.JTextField Packagetf;
    public javax.swing.JTextField Programtf;
    private javax.swing.JButton Registerbtn;
    public javax.swing.JTextField Statustf;
    public javax.swing.JTextField StudentMobiletf;
    public javax.swing.JTextField StudentNametf;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
